Independientes/urls.py
from django.urls import path, include # type: ignore
from . import views
from .views import IndependienteViewSet, CalculosViewSet
from django.urls import path, include # type: ignore
from rest_framework.routers import DefaultRouter

independiente_router = DefaultRouter()
independiente_router.register(r'independienterest', IndependienteViewSet)

calculos_router = DefaultRouter()
calculos_router.register(r'calculosrest', CalculosViewSet)


urlpatterns = [

    path('calcularinde/<str:numero_identificacion>/', views.CalculosGenerales.calcular_aportes, name='calcularinde'),

    
    
    
    path('inde',include(independiente_router.urls)),
    path('calcu',include(calculos_router.urls)),
 
 
]

PayMaster/urls.py
from django.contrib import admin # type: ignore
from django.urls import include, path  # type: ignore
from django.conf.urls.static import static  # type: ignore
from . import settings
from . import views
from rest_framework.documentation import include_docs_urls # type: ignore



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homePrincipal,name='homeGeneral'),
    path('menu', views.menu,name='menu'),

    path("independientes/", include ('Independientes.urls')),
    path("empresarial/", include ('Empresarial.urls')),
    path('docs/',include_docs_urls(title='Documentation REST Independiente')),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Independientes/models.py
from django.db import models  # type: ignore
from django.contrib.auth.hashers import make_password, check_password  # type: ignore
from django.contrib.auth.models import Permission  # type: ignore
from django.contrib.auth.hashers import check_password as django_check_password  # type: ignore
from django.core.validators import MaxValueValidator,MinValueValidator  # type: ignore
from django.utils import timezone  # type: ignore
from django.utils.timezone import timedelta  # type: ignore
from rest_framework import serializers # type: ignore

# Create your models here.
class Independiente(models.Model):


    numero_identificacion = models.IntegerField(primary_key=True)
    primer_nombre = models.CharField(max_length=30)
    segundo_nombre = models.CharField(max_length=30, blank=True, null=True)
    primer_apellido = models.CharField(max_length=30)
    segundo_apellido = models.CharField(max_length=30, blank=True, null=True)
    estado_civil = models.CharField(max_length=20)
    tipo_documento = models.CharField(max_length=50 )
    correo = models.EmailField(unique=True)
    celular = models.CharField(max_length=15)
    genero = models.CharField(max_length=10)
    fecha_nacimiento = models.DateField()
    fecha_exp_documento = models.DateField()
    imagen=models.ImageField(upload_to='photos')

    def __str__(self):
        return self.primer_nombre
    
class Calculos(models.Model):
    documento = models.ForeignKey(Independiente, on_delete=models.CASCADE)
    salud=models.FloatField(blank=True, null=True)
    pension=models.FloatField(blank=True,null=True)
    arl=models.FloatField(blank=True,null=True)
    salarioBase=models.FloatField(blank=True,null=True)
    cajaCompensacion=models.FloatField(blank=True,null=True)
    FSP=models.FloatField(blank=True,null=True)
    
class DatosCalculos(models.Model):

    documento = models.ForeignKey(Independiente, on_delete=models.CASCADE)
    salarioBase=models.FloatField(null=True, blank=True)
    ibc=models.FloatField(validators=[MaxValueValidator(100),MinValueValidator(40)],null=True)
    salud=models.FloatField( max_length=50, default=12.5)
    pension=models.FloatField(max_length=50, default=16)
    arl=models.FloatField(blank=True,null=True, max_length=25)
    CCF=models.FloatField(blank=True,null=True,  max_length=25)
    FSP=models.FloatField(blank=True,null=True,  max_length=25)

Empresarial/forms.py
from django import forms   # type: ignore 
from .models import Empleado,Empresa, Calculos, Novedades

class EmpresaForm(forms.ModelForm):
    class Meta:
        model = Empresa
        fields = '__all__'

class EmpleadoForm(forms.ModelForm):
    class Meta:
        model = Empleado
        fields ='__all__'
        
        
        # ['numero_identificacion', 'primer_nombre', 'segundo_nombre', 'primer_apellido', 'segundo_apellido', 'estado_civil']

    # def __init__(self, *args, **kwargs):
    #     super(EmpleadoForm, self).__init__(*args, **kwargs)
    #     readonly_fields = ['numero_identificacion', 'primer_nombre', 'segundo_nombre', 'primer_apellido', 'segundo_apellido']
    #     for filtro in self.fields:
    #         if filtro in readonly_fields:
    #             self.fields[filtro].widget.attrs['readonly'] = True

class LoginForm(forms.Form):
    numero_identificacion = forms.IntegerField(label='Número de identificación')
    contrasena = forms.CharField(label='Contraseña', widget=forms.PasswordInput)


class RecuperarContrasenaForm(forms.Form):
    numero_identificacion = forms.IntegerField(label='Número de Identificación')


class PasswordResetForm(forms.Form):
    token = forms.CharField(label='Token', max_length=255)
    new_password = forms.CharField(label='Nueva Contraseña', widget=forms.PasswordInput)
    confirm_password = forms.CharField(label='Confirmar Contraseña', widget=forms.PasswordInput)
    

class NovedadesForm(forms.ModelForm):
    class Meta:
        model = Novedades
        fields = [
            'HorasExDiu',
            'HorasExNoc',
            'HorasExFestivaNoc',
            'HorasExFestivaDiu',
            'recargoDiuFes',
            'recargoNoc',
            'recargoNocFest',
        ]

    def clean(self):
        cleaned_data = super().clean()
        
        # Definir una función para obtener el valor del campo o devolver 0 si es None o vacío
        def get_valor_campo(campo):
            valor = cleaned_data.get(campo)
            return valor if valor is not None and valor != '' else 0
        
        # Obtener los valores de los campos y manejar valores vacíos o None
        horas_ex_diu = get_valor_campo('HorasExDiu')
        horas_ex_noc = get_valor_campo('HorasExNoc')
        horas_ex_festiva_noc = get_valor_campo('HorasExFestivaNoc')
        horas_ex_festiva_diu = get_valor_campo('HorasExFestivaDiu')
        recargo_diu_fes = get_valor_campo('recargoDiuFes')
        recargo_noc = get_valor_campo('recargoNoc')
        recargo_noc_fest = get_valor_campo('recargoNocFest')

        # Calcular la suma total de horas
        horas_totales = (
            horas_ex_diu + horas_ex_noc +
            horas_ex_festiva_noc + horas_ex_festiva_diu
        )

        # Validar si la suma total de horas excede 48
        if horas_totales > 48:
            raise forms.ValidationError('La suma de horas no puede exceder 48.')

        return cleaned_data

Independientes/forms.py
from django import forms   # type: ignore 
from .models import Independiente, DatosCalculos


class IndependienteForm(forms.ModelForm):
    class Meta:
        model = Independiente
        fields ='__all__'


class DatosCalculosForm(forms.ModelForm):
    class Meta:
        model = DatosCalculos
        fields = ['salarioBase', 'ibc', 'salud', 'pension', 'arl', 'CCF']

Independientes/views.py
from rest_framework.views import APIView # type: ignore
from rest_framework.response import Response # type: ignore
from rest_framework import status# type: ignore
from rest_framework import viewsets# type: ignore
from . serializer import IndependienteSerializer, CalculosSerializer
from . models import Independiente, Calculos,DatosCalculos

from django.shortcuts import render # type: ignore
from .forms import DatosCalculosForm
from django.http import HttpRequest # type: ignore




class IndependienteViewSet(viewsets.ModelViewSet):
    queryset=Independiente.objects.all()
    serializer_class=IndependienteSerializer

class IndependienteCreate(APIView):
    def post(self, request, format=None):
        serializer = IndependienteViewSet(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class CalculosViewSet(viewsets.ModelViewSet):
    queryset=Calculos.objects.all()
    serializer_class=CalculosSerializer



class CalculosGenerales(HttpRequest):
    def calcular_aportes(request, numero_identificacion):
        
            independiente = Independiente.objects.get(pk=numero_identificacion)

# Busca la instancia de DatosCalculos relacionada con el independiente
            try:
                datos_calculos = DatosCalculos.objects.get(documento=independiente)
            except DatosCalculos.DoesNotExist:
                datos_calculos = None

            if request.method == 'POST':
                form = DatosCalculosForm(request.POST, instance=datos_calculos)
                if form.is_valid():
                    # Asigna la relación con independiente si es una nueva instancia
                    calculos = form.save(commit=False)
                    if datos_calculos is None:
                        calculos.documento = independiente
                    calculos.save()
                    # Aquí puedes redirigir a otra página o renderizar una respuesta
          
                datos_calculos=DatosCalculos.objects.filter(documento=independiente)#esto es para traer los datos                 
                
                for objeto in datos_calculos:
                    
                    salario_base = objeto.salarioBase
                    nivel_arl = objeto.arl
                    ccf = objeto.CCF
                    porcentaje_ibc=objeto.ibc
                    
                
                ibc = salario_base * (porcentaje_ibc/100)
                if ibc<1300000:
                    ibc=1300000
                    
                salud = ibc * 0.125
                pension = ibc * 0.16
                
                
             
                # fsp =fsp
            
                arl = CalculosGenerales.calcular_arl (ibc,nivel_arl)
                
                
                if ccf == 'Si':
                    ccf = ibc * 0.04
                else:
                    ccf = 0
                
                salud = salud
                pension = pension
                # fsp = fsp
                
                context = {
                    'independiente': independiente,
                    'salario_base': salario_base,
                    'ibc': ibc,
                    'salud': salud,
                    'pension': pension,
                    'arl': arl,
                    'ccf': ccf,
                    # 'fsp': fsp
                }
                
                return render(request, 'independientes/resultado_calculos.html', context)
            
            
            else:
                form = DatosCalculosForm()
        
            return render(request, 'independientes/calcular_aportes.html', {'form': form, 'independiente': independiente})
    


    def calcular_arl(ibc, arl_nivel):
        
        if arl_nivel == '1':
                arl = ibc * 0.00522
        elif arl_nivel == '2':
                arl = ibc * 0.01044
        elif arl_nivel == '3':
                arl = ibc * 0.02436
        elif arl_nivel == '4':
                arl = ibc * 0.04350
        elif arl_nivel == '5':
                arl = ibc * 0.06960
        elif arl_nivel == '0':
                arl = 0
        return (arl)
        

templates/independientes/calcular_aportes.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Calcular Aportes</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/cssTabla.css' %}">
</head>
<body>
    <div class="container">
        <h1>Calcular Aportes para {{ independiente.primer_nombre }} {{ independiente.primer_apellido }}</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form}}
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>
</body>
</html>

templates/independientes/dashboard.html
<!-- dashboard.html -->

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
</head>
<body>
    <h2>Bienvenido al Dashboard</h2>

    <p>Hola, {{ request.user.username }}</p>

    <a href="{% url 'logout' %}">Cerrar sesión</a>
</body>
</html>

templates/independientes/editarIndependi.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'image/logo2.png' %}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fomularios.css' %}" />
    <title>Editar Empleado</title>
</head>
<body>
    <div class="contenedor">
        <h1>Editar Empleado</h1>
        {% if request.session.estadoSesion %}
         
            {% if request.session.permisos == 'Independiente' %}
                {% if independi %}
                    <h2>Bienvenido {{ independi.primer_nombre }}</h2>
                    <form action="{% url 'actualizarIndependiente' independi.numero_identificacion %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Modificar</button>
                    </form>
                {% else %}
                    <h2>El usuario no encontrado</h2>
                {% endif %}
            {% else %}
                <h2>El usuario no tiene permisos para editar</h2>
            {% endif %}
        {% else %}
            <h2>El usuario no ha iniciado sesión</h2>
        {% endif %}
        <a href="{% url 'homeIndependiente' %}" class="btn btn-danger">Volver</a>
    </div>

    <script>
        window.addEventListener('beforeunload', function(event) {
        
            fetch('{% url "cerrar_sesion" %}', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                body: JSON.stringify({})
            }).then(response => {
                if (response.ok) {
                 
                    window.location.href = '{% url "login" %}';
                }
            }).catch(error => {
                console.error('Error al cerrar sesión:', error);
               
            });
        });
    </script>
</body>
</html>

templates/independientes/formularioCalcular.html
<!DOCTYPE html>
<html>
<head>
    <title>Formulario de Cálculo</title>
</head>
<body>
    <h1>Formulario de Cálculo</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
</body>
</html>

templates/independientes/home.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/tablas.css' %}">
    <link rel="shortcut icon" href="{% static 'image/logo2.png' %}" type="image/x-icon">
    <title>Permisos del Usuario</title>
    
</head>
<>
    <div class="contenedor">
        {% if request.session.estadoSesion %}
            {% if request.session.permisos == 'Independiente' %}

                {% if independi %}
                    <h1>Bienvenido {{ independi.primer_nombre }}</h1>
                    
                    <table border="1">
                        <tr>
                            <th>Identificación</th>
                            <th>Nombre</th>
                            <th>Celular</th>
                            <th>Imagen</th>
                            <th colspan='2'>Acción</th>
                        </tr>
                        <tr>
                            <td>{{ independi.numero_identificacion }}</td>
                            <td>{{ independi.primer_nombre }} {{ independi.primer_apellido }}</td>
                            <td>{{ independi.celular }}</td>
                            <td><img src="{{ independi.imagen.url }}" alt="Imagen" width="50"></td>
                            <td>
                                <a class="a"  href="{% url 'editarIndependiente' independi.numero_identificacion %}" class="btn btn-info">Editar datos</a>
                                <a class="a"  href="{% url 'eliminaremple' independi.numero_identificacion %}" class="btn btn-danger">Eliminar</a>
                                <a class="a"  href="{% url 'calcularinde' independi.numero_identificacion %}" class="btn btn-primary">Calcular</a>
                            </td>
                        
                        </tr>
                    </table>

                    <form id="logout-form" method="POST" action="{% url 'cerrar_sesion_redirect' %}">
                        {% csrf_token %}
                        <button class="link cerrar" type="submit">Cerrar Sesión</button>
                    </form>
                </div>
                
            {% else %}
                <h1>El usuario {{ request.user.username }} no tiene perfil de Independiente</h1>
            {% endif %}

        {% else %}
            <h1>El usuario no tiene permisos</h1>
        {% endif %}
    {% else %}
        <h1>El usuario no ha iniciado sesión</h1>
    {% endif %}

    <script>
        window.addEventListener('popstate', function(event) {
            // Prevenir el comportamiento por defecto
            event.preventDefault();
    
            // Enviar la solicitud POST para cerrar sesión
            fetch('{% url "cerrar_sesion" %}', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                body: JSON.stringify({})
            }).then(response => {
                if (response.ok) {
                    // Redirigir a la página de inicio de sesión después de cerrar sesión
                    window.location.href = '{% url "login" %}';
                }
            }).catch(error => {
                console.error('Error al cerrar sesión:', error);
                // Opcional: Manejar errores si es necesario
            });
        });
    </script>
</body>
</html>

templates/independientes/login.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login_in.css' %}">
    <link rel="shortcut icon" href="{% static 'image/logo2.png' %}" type="image/x-icon">
    <title>Iniciar sesión</title>
</head>
<body>
    <div class="contenedeor">
        <div class="logo">
            <img src="{% static 'image/logo2.png' %}" alt="PayMaster">
            <p>PayMaster</p>
        </div>
        <div class="volverB">
            <a class="link volver" href="{% url 'menu' %}">Volver</a>
        </div>
        <div class="login">
            <p id="titulo">Iniciar sesión</p>
            {% if messages %}
                <div>
                    {% for message in messages %}
                        <p>{{ message }}</p>
                    {% endfor %}
                </div>
            {% endif %}
            <form class="formulario" method="post">
                {% csrf_token %}
                <label for="id_numero_identificacion" class="form-label">Número de identificación:</label>
                <input type="number" class="form-control" id="id_numero_identificacion" name="numero_identificacion" required>

                <label for="id_contrasena" class="form-label">Contraseña:</label>
                <input type="password" class="form-control" id="id_contrasena" name="contrasena" required>
                <div class="button">
                    <button class="boton" type="submit" class="btn btn-primary">Iniciar sesión</button>
                </div>
            </form>

            <a class="link" href="{% url 'registrarIndependiente' %}">Registrarse</a>
            <a class="link" href="{% url 'recuperar_contrasena' %}">Recuperar contraseña</a>
        </div>
    </div>
</body>
</html>

templates/independientes/password_reset.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login_in.css' %}">
    <link rel="shortcut icon" href="{% static 'image/logo2.png' %}" type="image/x-icon">    <title>Iniciar sesión</title>
    <title>Iniciar sesión</title>
    
</head>
<body>
    <div class="contenedeor">
        <div class="logo">
            <img src="{% static 'image/logo2.png' %}" alt="PayMaster">
            <p>PayMaster</p>
        </div>
        <div class="volverB">
            <a class="link volver" href="{% url 'login' %}">Volver</a>
        </div>
        <div class="login">
            <h2>Iniciar sesión</h2>
            {% if messages %}
                <div>
                    {% for message in messages %}
                        <p>{{ message }}</p>
                    {% endfor %}
                </div>
            {% endif %}
            <form class="formulario" method="post">
                {% csrf_token %}
                {{ form }}
                
                <div class="button">
                    <button class="boton" type="submit">Guardar</button>
                </div>

            </form>
        </div>
    </div>
</body>
</html>

templates/independientes/recuperar_contrasena.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login_in.css' %}">
    <link rel="shortcut icon" href="{% static 'image/logo2.png' %}" type="image/x-icon">    <title>Iniciar sesión</title>
    <title>Recuperar Contraseña</title>
   
</head>
<body>
    <div class="contenedeor">
        <div class="logo">
            <img src="{% static 'image/logo2.png' %}" alt="PayMaster">
            <p>PayMaster</p>
        </div>
        <div class="volverB">
            <a class="link" href="{% url 'login' %}">Volver</a>
        </div>
        <div class="login">
            <p id="titulo">Recuperar mi Contraseña</p>

            <form class="formulario" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="button">
                    <button class="boton"  type="submit">Enviar solicitud</button>
                </div>
            </form>
            
            <a class="link" href="{% url 'password_reset' %}" >Tengo token</a>
        </div>
    </div>
</body>
</html>

templates/independientes/registroIndependi.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'image/logo2.png' %}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fomularios.css' %}" />
    <title>Menú de Inicio</title>

</head>
<body>
    <div class="contenedor">
        <h2>REGISTRO EMPPLEADOS</h2>
        <form action= "{% url 'registrarIndependiente' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <button type="submit" id="btnEnviar" class=button>ENVIAR</button>
        </form>
        <a class="link" href="{% url 'login' %}">Volver</a>
    </div>
</body>
</html>

templates/independientes/resultado_calculos.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Resultados de Cálculos</title>
</head>
<body>
    <div class="container mt-5">
        <h2>Resultados de Cálculos para {{ independiente.primer_nombre }} {{ independiente.primer_apellido }}</h2>
        
        <table class="table">
            <thead>
                <tr>
                    <th>Concepto</th>
                    <th>Valor</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Salario Base</td>
                    <td>{{ salario_base }}</td>
                </tr>
                <tr>
                    <td>IBC</td>
                    <td>{{ ibc }}</td>
                </tr>
                <tr>
                    <td>Salud</td>
                    <td>{{ salud }}</td>
                </tr>
                <tr>
                    <td>Pensión</td>
                    <td>{{ pension }}</td>
                </tr>
                <tr>
                    <td>ARL</td>
                    <td>{{ arl }}</td>
                </tr>
                <tr>
                    <td>CCF</td>
                    <td>{{ ccf }}</td>
                </tr>
                {% comment %} <tr>
                    <td>FSP</td>
                    <td>{{ fsp }}</td>
                </tr> {% endcomment %}
            </tbody>
        </table>
        
        <a href="{% url 'homeIndependiente' %}" class="btn btn-primary">Volver</a>
    </div>
</body>
</html>